### ISSUE TITLE
Optional 제안

### ISSUE THREAD

**Issue by claion-mattdony** [hard-coders/fastcampusapi#1]
https://github.com/hard-coders/fastcampusapi/blob/b9d537ff734ebf22e395b3007e9061ccb0e1d736/lib/schema.py#L21

안녕하세요. Fastcampus에서 강의를 보며 따라하던 중 오류가 나서 확인해 보니
schema.py 파일의 User 클래스에 필수값이 아닌 파라미터에 대해 Optional 처리가 안되어 있더라구요.
(https://core.telegram.org/bots/api#user)

제가 username 을 설정하지 않아서 난 에러지만... 저와 같은 초보자는 오류가 나면 당황하면서
멘탈에 데미지가 가해져서... 제안 드려봅니다^^

아 참고로 "한 번에 끝내는 파이썬 웹 개발 초격차 패키지 Online"
Part13 / CH01_03 번에서 v.0.1.2 로
webhook 실습하다가 발견했습니다.

좋은 강의 감사합니다!!

==========================================================

class User(BaseModel):
    id: int
    is_bot: bool
    first_name: str
    last_name: Optional[str]
    username: Optional[str]
    language_code: Optional[str]

**Comment by claion-mattdony** [comment]
바로 다음 강의를 듣다보니 username 을 nullable=False 제약 조건 주신걸 확인했습니다.
강사님께서 예제로 만들어 주신 코드를 정상 작동하기 위해선 무조건 필요한 부분이라
일부러 Optional로 안하신게 아닐까 하는 생각이 들었습니다.

다시 한번 좋은 강의 감사합니다!!

**Comment by hard-coders** [comment]
@claion-mattdony 
안녕하세요, 근래 휴식기를 가지느라 지금 봤습니다.

코멘트 주신대로 필수값이기 때문에 제약조건을 걸어 텔래그램 API를 호출하기 이전에 서버에서 미리 데이터 검증을 위해 그렇게 작성했습니다.
데이터 모델에 맞게 FastAPI가 검증을 하기 때문에 따로 방어코드를 작성할 필요가 없습니다. FastAPI의 장점 중 하나입니다:)

강의 들어주셔서 감사하고, 앞으로도 FastAPI 잘 활용하셨으면 합니다😃

(문제가 없기 때문에 이슈는 닫겠습니다)
